###
FROM node:lts-alpine3.19 as run

RUN set -eux \
    && apk add --no-cache git \
    # installs right from tarball from the github. still needs 'git' tho.
    && npm install -g --save "https://github.com/vigilancer/ergogen/tarball/myfork" \
    # saves around 23MB
    && rm -rf /root/.npm

VOLUME ["/work/output", "/work/input"]
WORKDIR /work

ENTRYPOINT ["ergogen"]

CMD ["/work/input/keyboard.yaml", "--clean", "--debug", "--output=/work/output"]